version: "3"

services:
  application:
    container_name: restapi-docker-test
    restart: on-failure
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    networks:
      - rest-api-test

networks:
  rest-api-test:
